---
layout: cv
title: Spencer Helsley's Resume
---
# Spencer Helsley
Aspiring Psychologist, Student, Family Man

<div id="webaddress">
<a href="spencerhelsley72@gmail.com">My email</a>
| <a href="www.linkedin.com/in/spencer-helsley-98398530b">My linkedin Page</a>
</div>



## EDUCATION
#### Psychology
##### Brigham Young University - Idaho
###### • Bachelors in Psychology
April 2024 - July 2028
Rexburg, Idaho
## High School Diploma
Skyline High School



September 2017 - June 2021
Idaho Falls, Idaho

• Notable classes include: AP Physics, AP US History, AP Calculus, College-Level trigonometry, AP Government

## EXPERIENCE
June 2025 - Present
Rexburg, ID
Direct Care Staff
A Bit of Love-CARF

Collaboration with direct care staff to assess needs of children with trauma
• Teaching correct social behaviors of children using principles of ABA
• Cleaning up a house based on standards of facility

August 2024 - Present
Rexburg, Idaho
New Student Mentor/Coordinator
Brigham Young University-Idaho

• Directed a group of 44 students through first semester of college
• Developed interpersonal communication skills by open communication with new students
• Devised facilitation strategies included hearing ideas of mentors


April 2025 - July 2025
Rexburg Idaho
Teacher's Assistant
Brigham Young University-Idaho

• Encouraged students through grading assignments and giving feedback
• Collaborated with professor to assess  needs of students

August 2021 - August 2023
Rio de Janeiro, Brazil

Representative
The Church of Jesus Christ of Latter-Day Saints Rio de Janeiro

• Led weekly trainings of 8-10 volunteers to revamp communication with others, goal settings and following up on plans
• Persevered through long days of work
• De-escalated difficult interactions in a professional manner
• Collaborated with volunteers on weekly and monthly progress

## AWARDS

• The Eagle Scout Award

## SKILLS
Collaborative, Bilingual (Portuguese), and Goal-oriented

## CERTIFICATIONS
• QPR Certification
• CPR Certification
• RBT Certification/40hr Course
• MANDT Certification

